// Generated by Haxe 4.3.3
(function ($global) { "use strict";
class Main {
	static main() {
		let values = [1,2,3,4,5];
		let total = 0;
		let _g = 0;
		while(_g < values.length) total += values[_g++];
		console.log("src/Main.hx:14:","Haxe" + " is running in " + "iOS Swift Playground");
		console.log("src/Main.hx:15:","sum(1...5) = " + total);
	}
}
class haxe_iterators_ArrayIterator {
	constructor(array) {
		this.current = 0;
		this.array = array;
	}
	hasNext() {
		return this.current < this.array.length;
	}
	next() {
		return this.array[this.current++];
	}
}
{
}
Main.main();
})({});
